---
name: GuardDog

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  guarddog:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Scan dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
        with:
          python-version: "3.x"

      - name: Install GuardDog
        run: |
          sudo apt-get install -y libgit2-dev
          pip install guarddog==2.6.0

      - name: Generate requirements.txt
        run: |
          python3 -mvenv venv
          . venv/bin/activate
          pip install -e .
          pip freeze | grep -v -f requirements-guarddog-ignore.txt | tee requirements.txt

      - name: Check requirements.txt
        run: |
          cat requirements.txt

      - name: Run guarddog
        run: |
          guarddog pypi verify requirements.txt --output-format sarif --exclude-rules repository_integrity_mismatch -x single_python_file > guarddog.sarif

      - name: View SARIF file
        run: |
          cat guarddog.sarif

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@fe4161a26a8629af62121b670040955b330f9af2  # v4.31.6
        with:
          category: guarddog-builtin
          sarif_file: guarddog.sarif
